/*  $Id: Archive.H 1474 2006-02-04 23:00:32Z turian $
 *  Copyright (c) 2004-2006, New York University. All rights reserved. */
/*!
 *  \file Archive.H
 *  $LastChangedDate: 2006-02-04 18:00:32 -0500 (Sat, 04 Feb 2006) $
 *  $Revision: 1474 $
 */
/*!
 *  \class Archive
 *  \brief WRITEME
 *
 *  WRITEME
 *
 */

#ifndef __Archive_H__
#define  __Archive_H__

#include <boost/archive/text_oarchive.hpp>
#include <boost/archive/text_iarchive.hpp>
#include <boost/serialization/base_object.hpp>
#include <boost/serialization/utility.hpp>
#include <boost/serialization/shared_ptr.hpp>
#include <boost/serialization/deque.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/hash_map.hpp>
#include <boost/serialization/hash_set.hpp>
#include <boost/serialization/set.hpp>

#endif /* __Archive_H__ */
