/*  $Id: Sentence.H 1657 2006-06-04 03:03:05Z turian $ 
 *  Copyright (c) 2004-2006, New York University. All rights reserved. */
/*!
 *  \file Sentence.H
 *  $LastChangedDate: 2006-06-03 23:03:05 -0400 (Sat, 03 Jun 2006) $
 *  $Revision: 1657 $
 */
/*!
 *  \class Sentence
 *  \brief A dummy class, created merely so that we can assign ID%s to sentences.
 *
 */

#ifndef __Sentence_H__
#define  __Sentence_H__

class Sentence {
};

#endif /* __Sentence_H__ */
